FROM eclipse-temurin:17-jdk
WORKDIR /app

COPY target/main-0.0.1-SNAPSHOT.jar app.jar
COPY test-network/organizations /app/organizations
ENV FABRIC_MSP_ID=Org1MSP
ENV FABRIC_CHANNEL_NAME=mychannel
ENV FABRIC_CHAINCODE_NAME=basic
ENV FABRIC_PEER_ENDPOINT=fabric.mired.com:7051
ENV FABRIC_OVERRIDE_AUTH=peer0.org1.example.com
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
